#!/usr/bin/env python3
"""
Export all seeded data from the reno-record TiDB Cloud database to seed.sql.

Usage:
  cd /home/ubuntu/reno-record
  python3 drizzle/export-seed.py

Requires DATABASE_URL to be set in the environment (injected automatically in sandbox).
"""
import subprocess
import os
import re

url = os.environ.get("DATABASE_URL", "")
if not url:
    print("ERROR: DATABASE_URL not set in environment")
    exit(1)

match = re.match(r"mysql://([^:]+):([^@]+)@([^:]+):(\d+)/(.+)", url)
if not match:
    print(f"ERROR: Could not parse DATABASE_URL")
    exit(1)

user, password, host, port, dbname = match.groups()
dbname = dbname.split("?")[0]
print(f"Connecting to {host}:{port}/{dbname}")

TABLES = [
    "users",
    "agencies",
    "actors",
    "timeline_events",
    "documents",
    "violation_tags",
    "document_violation_tags",
    "actor_document_links",
    "actor_timeline_links",
    "stories",
    "audit_log",
]

output_lines = [
    "-- ============================================================",
    "-- Reno Record — Database Seed Export",
    "-- Generated by drizzle/export-seed.py",
    "-- Run AFTER schema migrations to restore all seeded data",
    "-- ============================================================",
    "",
    "SET FOREIGN_KEY_CHECKS = 0;",
    "",
]

env = {**os.environ, "MYSQL_PWD": password}

for table in TABLES:
    print(f"  Exporting {table}...")
    result = subprocess.run(
        [
            "mysqldump",
            f"--host={host}",
            f"--port={port}",
            f"--user={user}",
            "--ssl-mode=REQUIRED",
            "--no-create-info",
            "--skip-triggers",
            "--complete-insert",
            "--skip-extended-insert",
            "--no-tablespaces",
            dbname,
            table,
        ],
        capture_output=True,
        text=True,
        env=env,
    )

    if result.returncode == 0:
        inserts = [line for line in result.stdout.splitlines() if line.startswith("INSERT INTO")]
        if inserts:
            output_lines.append(f"-- Table: {table} ({len(inserts)} rows)")
            output_lines.extend(inserts)
            output_lines.append("")
            print(f"  ✓ {table}: {len(inserts)} rows")
        else:
            output_lines.append(f"-- Table: {table} (empty)")
            output_lines.append("")
            print(f"  - {table}: empty")
    else:
        print(f"  ERROR: {result.stderr[:200]}")

output_lines.append("SET FOREIGN_KEY_CHECKS = 1;")
output_lines.append("")

output = "\n".join(output_lines)
output_path = os.path.join(os.path.dirname(__file__), "seed.sql")
with open(output_path, "w") as f:
    f.write(output)

print(f"\n✓ Seed export written to: {output_path}")
print(f"  Size: {len(output):,} bytes")
print(f"  INSERT statements: {output.count('INSERT INTO')}")
